# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436f992f55b2bbcfeb532ea544b228196bf253951204932b7a4779f0e9b6847d71ee8c1a5bcea05c0721bb3b1a4e153f13e4917f2a3ee2bbe09f28cf9037f797

test:
  secret_key_base: 6bb7affc98b5ba28e998093209ddd32fd368c027ea095472e3708ce6237bbede6c834593339ad38bcdf870241483a60fff10826170340aa48d619c9becb6fb45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
